### ISSUE TITLE
Feature wanted , create spanish transtlation of Readme.md

### ISSUE THREAD

**Issue by hectorpasarin** [npedidos/web#1]
Make Readme.md available in spanish, same way there is a translation of readme.md in [npedidos/rest-api](https://github.com/npedidos/rest-api)

**Comment by hectorpasarin** [comment]
Please, I wold like to work in this issue for the hacktoberfest 2022, 
Could you assign to me?
thanks.

**Comment by nmarulo** [comment]
@hectorpasarin 
Hi 👋, thank you very much for your interest.
Currently we are only working on the rest-api project, the web project has not been started yet, that's why I didn't include this project in the hacktoberfest, because it is a lot of work for one person. Also, the readme information is the default generated and will be completely rewritten.
